/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'

const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/_authenticated/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof AuthenticatedHomeRoute
}
export interface FileRoutesByTo {
  '/home': typeof AuthenticatedHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/home': typeof AuthenticatedHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/home'
  id: '__root__' | '/_authenticated/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
